import { Request, Response } from 'express';
import AlraghebService from '../services/AlraghebService';

export const createNewOrder = async (req: Request, res: Response) => {
  try {
    const { productId, qty, playerId } = req.body;

    // Validate inputs
    if (!productId || !qty || !playerId) {
      return res.status(400).json({ 
        success: false, 
        message: 'Missing required parameters: productId, qty, or playerId' 
      });
    }

    // Call the service to create the order
    // order_uuid is automatically generated by the service if not provided
    const result = await AlraghebService.createOrder(productId, qty, playerId);

    // If the API returns success
    if (result && result.status === 'OK') {
      return res.status(200).json({
        success: true,
        message: 'Order created successfully',
        data: result.data // e.g. { "order_id": "...", "status": "accept" }
      });
    } else {
      return res.status(400).json({
        success: false,
        message: 'Failed to create order',
        data: result
      });
    }
  } catch (error: any) {
    // Handle specific errors based on error_code from Alragheb API
    console.error('Alragheb API Error:', error);

    const errorCode = error.code;
    const errorMessage = error.message;

    // 100: Insufficient balance -> 402 Payment Required
    if (errorCode === 100) {
      return res.status(402).json({
        success: false,
        message: errorMessage,
        error_code: errorCode
      });
    }

    // Validation errors (e.g., qty not available, blocked player) -> 400 Bad Request
    if ([105, 106, 107, 108, 109, 110, 112, 113].includes(errorCode)) {
      return res.status(400).json({
        success: false,
        message: errorMessage,
        error_code: errorCode
      });
    }
    
    // Auth and IP errors -> 401 Unauthorized or 403 Forbidden
    if ([120, 121, 122].includes(errorCode)) {
      return res.status(401).json({
        success: false,
        message: 'Authentication failed with provider',
        error_code: errorCode
      });
    }
    
    if (errorCode === 123) {
      return res.status(403).json({
        success: false,
        message: 'Server IP not allowed by provider',
        error_code: errorCode
      });
    }

    // Server/Maintenance errors -> 503 Service Unavailable
    if ([111, 130].includes(errorCode)) {
      return res.status(503).json({
        success: false,
        message: errorMessage,
        error_code: errorCode
      });
    }

    // General fallback -> 500 Internal Server Error
    return res.status(500).json({
      success: false,
      message: errorMessage || 'Internal Server Error',
      error_code: errorCode || 500
    });
  }
};
